### PR TITLE
Implement support for AMD module loader

### PR DESCRIPTION
**Pull request by benediktvaldez**
With https://github.com/umdjs/umd/blob/master/amdWeb.js as a reference

### CODE REVIEW

**Comment by louim** [comment]
lgtm! :+1:

**Comment by louim** [comment]
@benediktvaldez would you mind adding relevant information to the readme?

**Comment by benediktvaldez** [comment]
@louim Sure, this should do, unless you would like something more detailed?

**Comment by benediktvaldez** [comment]
@louim were you waiting on something else from me to merge this? I have merged the latest version from you guys into this PR and bumped the version number - you will propably need to create a new release for bower to pick up this version.

**Comment by louim** [comment]
Thanks for the reminder, somehow the notification slipped by!

**Pull request merged**
